theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "memory"
display_type = "memory"
# format_mem = "{Mup}%"
# format_swap = "{SUp}%"
format_mem = "{mem_total_used}/{mem_total}({mem_total_used_percents})"
# format_swap = "{SUm}MB/{STm}MB({SUp}%)"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlan0"
# format = "{$ssid} {$signal_strength} {ip} {speed_down} {speed_up}"
format = "{ip} {ssid}{speed_down} {speed_up}"
interval = 5

[[block]]
block = "custom"
command = 'xkb-switch'
interval = 1

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m/%y %R"
